---
resource_types:
- name: teams-notification
  type: docker-image
  source:
    repository: fidelityinternational/concourse-teams-notification-resource
    tag: latest

resources:
- name: teams-alert
  type: teams-notification
  source:
    url: ((webhook))
    atc_username: ((atc_username))
    atc_password: ((atc_password))
    log_max_length: 13500

jobs:
- name: monitoring-test
  serial: true
  build_logs_to_retain: 20
  plan:
  - do:
    - task: successful-job
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: fidelityinternational/paas-tools-go
        run:
          path: bash
          args:
          - -exc
          - -o
          - pipefail
          - |
            find /lib | tail -n 100
      on_success:
        do:
        - put: teams-alert
          params:
            status: success
    - task: failing-job
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: fidelityinternational/paas-tools-go
        run:
          path: bash
          args:
          - -exc
          - -o
          - pipefail
          - |
            echo "HoHoHo"
            sleep 5
            ls dasfsd
            false
      on_failure:
        do:
        - put: teams-alert
          params:
            status: failure
    timeout: 5m
